### ISSUE TITLE
"Test" integration into results file

### ISSUE THREAD

**Issue by sdrobert** [vladimirnani/DjangoCommands#24]
Hi there,

I was wondering if it would be possible to have the "Django: Test All" command ported through the results file in ST, so that any errors could be traversed through Sublime.

Thank you,
Sean

**Comment by Proyecto513** [comment]
Do you mean like redirect test outputs to a temp file?

**Comment by Proyecto513** [comment]
Definitely the output from tests can't be pulled from python itself, it just does'nt catch the test progession just the setting up and destroying messages

**Comment by sdrobert** [comment]
Thanks for your time. To be honest, I'd entirely forgotten about this :/

**Comment by Proyecto513** [comment]
Don't worry, I stopped working on this package for over a year, but I
started working with Django again and I came across some new issues

El mar. 4, 2017 15:54, "Sean Robertson" <notifications@github.com> escribió:

Thanks for your time. To be honest, I'd entirely forgotten about this :/

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/vladimirnani/DjangoCommands/issues/24#issuecomment-284186425>,
or mute the thread
