### ISSUE TITLE
Runserver Not working with path contain space

### ISSUE THREAD

**Issue by wgf4242** [vladimirnani/DjangoCommands#27]
```
D:\Python\Python35-32\python.EXE: can't open file 'D:\wgf\My': [Errno 2] No such
 file or directory

D:\wgf\My Documents\GitHub\testform>
```

Path in "something\My Documents\something" not working.

**Comment by Proyecto513** [comment]
It must work with the latest release, thanks for your time reporting this issue

**Comment by wgf4242** [comment]
version 1.6.2 same problem.

![png](http://i283.photobucket.com/albums/kk320/wgf4242/2017-02-28_200028.png)

**Comment by Proyecto513** [comment]
It will be solved right away, the problem is that I fixed a related issue
and thought of it as solved but I forgot about the fact that run server
implements its own formatting function instead of the default one so I'm
gonna change that and ill push some changes within the day, do you have
troubles with another command?

**Comment by Proyecto513** [comment]
After some tweaking and extensive testing I am certain that this problem has being solved
